FROM public.ecr.aws/lambda/python:3.9

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code and necessary configurations
COPY app.py ${LAMBDA_TASK_ROOT}
COPY llmconfig.json ${LAMBDA_TASK_ROOT}
COPY system_instructions.txt ${LAMBDA_TASK_ROOT}
COPY utils/ ${LAMBDA_TASK_ROOT}/utils/
#COPY config/ ${LAMBDA_TASK_ROOT}/config/

# Set the CMD to your handler
CMD ["app.handler"]
